/**
 * Native Email Service for Track Side
 * Provides simplified, native email integration with concise content
 */

interface GameEvent {
  gameTime?: string;
  type: string;
  team: 'us' | 'them';
  label?: string;
  meta?: {
    isPK?: boolean;
  };
}

interface MatchData {
  timestamp: number;
  opponentName?: string;
  myScore: number;
  opponentScore: number;
  finalTime?: string;
  events: GameEvent[];
}

export interface EmailContent {
  subject: string;
  body: string;
  attachment: File;
}

export class NativeEmailService {
  private static instance: NativeEmailService;

  static getInstance(): NativeEmailService {
    if (!NativeEmailService.instance) {
      NativeEmailService.instance = new NativeEmailService();
    }
    return NativeEmailService.instance;
  }

  generateConciseEmailContent(matchData: MatchData): EmailContent {
    const subject = this.generateConciseSubject(matchData);
    const body = this.generateConciseBody(matchData);
    const attachment = this.generateCSV(matchData);

    return { subject, body, attachment };
  }

  private generateConciseSubject(matchData: MatchData): string {
    const date = new Date(matchData.timestamp).toLocaleDateString();
    const score = `${matchData.myScore}-${matchData.opponentScore}`;
    const opponent = matchData.opponentName || 'Opponent';
    
    return `Track Side Match Analysis: ${opponent} (${score}) - ${date}`;
  }

  private generateConciseBody(matchData: MatchData): string {
    const date = new Date(matchData.timestamp).toLocaleDateString();
    const score = `${matchData.myScore}-${matchData.opponentScore}`;
    const opponent = matchData.opponentName || 'Opponent';
    const duration = matchData.finalTime || 'Unknown';
    const events = matchData.events.length;
    
    const ourGoals = matchData.events.filter((e: GameEvent) => e.type === 'goal' && e.team === 'us').length;
    const theirGoals = matchData.events.filter((e: GameEvent) => e.type === 'goal' && e.team === 'them').length;
    
    // Streamlined email content - data-focused with clean formatting
    let body = `Track Side Match Report

Opponent: ${opponent}
Score: ${score}
Date: ${date}
Duration: ${duration}

Key Stats:
• Our Goals: ${ourGoals}
• Opponent Goals: ${theirGoals}
• Total Events: ${events}

Detailed data attached in CSV file.

---
Generated by Track Side Analytics
track-side.vercel.app`;

    return body;
  }

  private generateCSV(matchData: MatchData): File {
    // Filter relevant events only - coach-focused data
    const relevantEvents = matchData.events.filter(event => 
      ['goal', 'assist', 'turnover', 'foul', 'possession'].includes(event.type)
    );
    
    // Streamlined CSV headers - coach-focused
    const headers = ['Time', 'Event', 'Team', 'Details'];
    const rows = relevantEvents.map((event: GameEvent) => [
      event.gameTime || '',
      event.type || '',
      event.team === 'us' ? 'Us' : 'Them',
      event.label || ''
    ]);

    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');

    return new File([csvContent], 'track-side-match-data.csv', { type: 'text/csv' });
  }

  async openEmailClient(content: EmailContent): Promise<void> {
    const { subject, body } = content;
    
    // Create mailto URL with subject and body
    const params = new URLSearchParams({
      subject: subject,
      body: body
    });

    const mailtoUrl = `mailto:?${params.toString()}`;
    
    // Open email client
    window.location.href = mailtoUrl;
    
    // Note: CSV attachment requires user to manually attach
    // This is a limitation of mailto protocol
    console.log('CSV file ready for manual attachment:', content.attachment.name);
  }

  generateCSVDownload(matchData: MatchData): void {
    const csvFile = this.generateCSV(matchData);
    const url = URL.createObjectURL(csvFile);
    const a = document.createElement('a');
    a.href = url;
    a.download = csvFile.name;
    a.click();
    URL.revokeObjectURL(url);
  }
}

// Export singleton instance
export const nativeEmailService = NativeEmailService.getInstance();
