/**
 * Native Email Service for Track Side
 * Provides simplified, native email integration with concise content
 */

interface GameEvent {
  gameTime?: string;
  type: string;
  team: 'us' | 'them';
  label?: string;
  meta?: {
    isPK?: boolean;
  };
}

interface MatchData {
  timestamp: number;
  opponentName?: string;
  myScore: number;
  opponentScore: number;
  finalTime?: string;
  events: GameEvent[];
}

export interface EmailContent {
  subject: string;
  body: string;
  attachment: File;
}

export class NativeEmailService {
  private static instance: NativeEmailService;

  static getInstance(): NativeEmailService {
    if (!NativeEmailService.instance) {
      NativeEmailService.instance = new NativeEmailService();
    }
    return NativeEmailService.instance;
  }

  generateConciseEmailContent(matchData: MatchData): EmailContent {
    const subject = `Track Side: Our Team ${matchData.myScore}-${matchData.opponentScore} ${matchData.opponentName}`;
    const body = this.generateBeautifulBody(matchData);
    const attachment = this.generateCSV(matchData);

    return { subject, body, attachment };
  }

  private generateBeautifulBody(matchData: MatchData): string {
    const productionUrl = 'https://track-side.vercel.app';
    const summary = [
      `📊 MATCH SUMMARY`,
      `═══════════════════════════`,
      `🏆 Match: Our Team vs ${matchData.opponentName}`,
      `⚡ Our Team: ${matchData.myScore}, Opponent: ${matchData.opponentScore}`,
      `📅 Date: ${new Date(matchData.timestamp).toLocaleDateString()}`,
      `⏱️ Duration: ${matchData.finalTime || 'Unknown'}`,
      `📝 Events: ${matchData.events.length} total`,
      '',
      `📋 EVENT TIMELINE`,
      `═══════════════════════════`,
      ...matchData.events.slice().reverse().map(e => {
        const icon = e.type === 'goal' ? '⚽' : e.type === 'penalty' ? '🟨' : '📝';
        const team = e.team === 'us' ? '🔵' : '🔴';
        const teamLabel = e.team === 'us' ? 'Our Team' : matchData.opponentName;
        const pk = e.meta?.isPK ? ' (PK)' : '';
        return `${icon} [${e.gameTime}] ${team} ${e.label || 'Unnamed'} (${teamLabel})${pk}`;
      }),
      '',
      '📊 TEAM STATISTICS',
      '═══════════════════════════',
      `🔵 Our Team: ${matchData.myScore} goals`,
      `🔴 ${matchData.opponentName}: ${matchData.opponentScore} goals`,
      '',
      `🌐 View Live: ${productionUrl}`,
      '',
      'Generated by Track Side App'
    ].join('\n');
    
    return summary;
  }

  private generateCSV(matchData: MatchData): File {
    // Filter relevant events only - coach-focused data
    const relevantEvents = matchData.events.filter(event => 
      ['goal', 'assist', 'turnover', 'foul', 'possession'].includes(event.type)
    );
    
    // Streamlined CSV headers - coach-focused
    const headers = ['Time', 'Event', 'Team', 'Details'];
    const rows = relevantEvents.map((event: GameEvent) => [
      event.gameTime || '',
      event.type || '',
      event.team === 'us' ? 'Us' : 'Them',
      event.label || ''
    ]);

    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');

    return new File([csvContent], 'track-side-match-data.csv', { type: 'text/csv' });
  }

  async openEmailClient(content: EmailContent): Promise<void> {
    const { subject, body } = content;
    
    // Create mailto URL with subject and body
    const params = new URLSearchParams({
      subject: subject,
      body: body
    });

    const mailtoUrl = `mailto:?${params.toString()}`;
    
    // Open email client
    window.location.href = mailtoUrl;
    
    // Note: CSV attachment requires user to manually attach
    // This is a limitation of mailto protocol
    console.log('CSV file ready for manual attachment:', content.attachment.name);
  }

  generateCSVDownload(matchData: MatchData): void {
    const csvFile = this.generateCSV(matchData);
    const url = URL.createObjectURL(csvFile);
    const a = document.createElement('a');
    a.href = url;
    a.download = csvFile.name;
    a.click();
    URL.revokeObjectURL(url);
  }
}

// Export singleton instance
export const nativeEmailService = NativeEmailService.getInstance();
