const CSV_HEADERS = ['Timestamp', 'Game Time', 'Type', 'Team', 'Label', 'Is PK'];

const formatEventRow = (event) => [
    new Date(event.timestamp).toLocaleString(),
    event.gameTime,
    event.type,
    event.team,
    event.label || 'Unnamed',
    event.meta?.isPK ? 'Yes' : 'No'
];

const generateCSVContent = (events) => {
    const rows = events.map(formatEventRow);
    return [CSV_HEADERS.join(','), ...rows.map(row => row.join(','))].join('\n');
};

const downloadFile = (content, filename) => {
    const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    URL.revokeObjectURL(url);
};

const generateFilename = (opponentName) => {
    const date = new Date().toISOString().split('T')[0];
    return `match-${opponentName}-${date}.csv`;
};

// Enhanced CSV generation with metadata and production URL
const generateEnhancedCSVContent = (game) => {
    const productionUrl = 'https://track-side.vercel.app';
    const headers = [
        'Match ID',
        'Date',
        'Opponent',
        'Final Score',
        'Production URL',
        'Event Timestamp',
        'Game Time',
        'Event Type',
        'Team',
        'Player',
        'Is Penalty',
        'Notes'
    ];
    
    const matchInfo = [
        game.id || crypto.randomUUID(),
        new Date(game.timestamp || Date.now()).toLocaleString(),
        game.opponentName,
        `Our Team: ${game.myScore}, Opponent: ${game.opponentScore}`,
        productionUrl,
        '', '', '', '', '', '', ''
    ];
    
    const eventRows = game.events.map(event => [
        '', // Match ID (empty for events)
        '', // Date (empty for events)
        '', // Opponent (empty for events)
        '', // Final Score (empty for events)
        '', // Production URL (empty for events)
        new Date(event.timestamp).toLocaleString(),
        event.gameTime,
        event.type,
        event.team === 'us' ? 'Our Team' : game.opponentName,
        event.label || '',
        event.meta?.isPK ? 'Yes' : 'No',
        event.meta?.notes || ''
    ]);
    
    return [headers, matchInfo, ...eventRows]
        .map(row => row.map(cell => `"${cell}"`).join(','))
        .join('\n');
};

// Enhanced summary generation with better formatting and production URL
const generateEnhancedSummary = (game, formatTime, formatTimeForExport) => {
    const productionUrl = 'https://track-side.vercel.app';
    const summary = [
        `📊 MATCH SUMMARY`,
        `═══════════════════════════`,
        `🏆 Match: Our Team vs ${game.opponentName}`,
        `⚡ Our Team: ${game.myScore}, Opponent: ${game.opponentScore}`,
        `📅 Date: ${new Date(game.timestamp || Date.now()).toLocaleDateString()}`,
        `⏱️ Duration: ${formatTimeForExport ? formatTimeForExport(game.finalTime) : game.finalTime || 'Unknown'}`,
        `📝 Events: ${game.events.length} total`,
        '',
        `📋 EVENT TIMELINE`,
        `═══════════════════════════`,
        ...game.events.slice().reverse().map(e => {
            const icon = e.type === 'goal' ? '⚽' : e.type === 'penalty' ? '🟨' : '📝';
            const team = e.team === 'us' ? '🔵' : '🔴';
            const teamLabel = e.team === 'us' ? 'Our Team' : game.opponentName;
            const pk = e.meta?.isPK ? ' (PK)' : '';
            return `${icon} [${formatTime ? formatTime(e.gameTime) : e.gameTime}] ${team} ${e.label || 'Unnamed'} (${teamLabel})${pk}`;
        }),
        '',
        '📊 TEAM STATISTICS',
        '═══════════════════════════',
        `🔵 Our Team: ${game.myScore} goals`,
        `🔴 ${game.opponentName}: ${game.opponentScore} goals`,
        '',
        `🌐 View Live: ${productionUrl}`,
        '',
        'Generated by Track Side App'
    ].join('\n');
    
    return summary;
};

export const downloadCSV = (game) => {
    const csvContent = generateCSVContent(game.events);
    const filename = generateFilename(game.opponentName);
    downloadFile(csvContent, filename);
};

// Enhanced export functions
export const downloadEnhancedCSV = (game) => {
    const csvContent = generateEnhancedCSVContent(game);
    const date = new Date().toISOString().split('T')[0];
    const filename = `enhanced-match-${game.opponentName}-${date}.csv`;
    downloadFile(csvContent, filename);
};

export const copyEnhancedSummary = (game, formatTime, formatTimeForExport) => {
    const summary = generateEnhancedSummary(game, formatTime, formatTimeForExport);
    
    if (navigator.clipboard && navigator.clipboard.writeText) {
        return navigator.clipboard.writeText(summary);
    } else {
        // Fallback for older browsers
        const textArea = document.createElement('textarea');
        textArea.value = summary;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
        return Promise.resolve();
    }
};
